# Generated by Django 4.0.4 on 2022-04-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
