# Generated by Django 4.0.4 on 2022-04-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_delete_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CID', models.IntegerField()),
                ('firstName', models.TextField(max_length=100)),
                ('lastName', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('street', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('zipCode', models.TextField(max_length=100)),
            ],
            
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('DID', models.IntegerField()),
                ('shippingCost', models.TextField(max_length=100)),
                ('shippingTime', models.TextField(max_length=100)),
            ],
             
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('brand', models.TextField(max_length=100)),
                ('price', models.TextField(max_length=100)),
            ],
            
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('VID', models.IntegerField()),
                ('companyName', models.TextField(max_length=100)),
                ('CID', models.IntegerField()),
                ('PID', models.IntegerField()),
            ],
             
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,)),
                ('RID', models.IntegerField()),
                ('size', models.TextField(max_length=100)),
                ('brand', models.TextField(max_length=100)),
                ('price', models.TextField(max_length=100)),
                ('CID', models.IntegerField()),
            ],
           
        ),
    ]
