# Generated by Django 4.0.4 on 2022-04-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ingressflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngressFlow',
        ),
    ]
