# Generated by Django 4.0.4 on 2022-04-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_delete_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=30, verbose_name='CID')),
                ('firstName', models.CharField(max_length=120, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('street', models.CharField(max_length=300, verbose_name='Home Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=15, verbose_name='State')),
                ('zipCode', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DID', models.CharField(max_length=30, verbose_name='Delivery ID')),
                ('shippingCost', models.CharField(max_length=30, verbose_name='Shipping Cost')),
                ('shippingTime', models.CharField(max_length=30, verbose_name='Shipping Time')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=20, verbose_name='Product ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('brand', models.CharField(max_length=120, verbose_name='Brand')),
                ('price', models.CharField(max_length=12, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.CharField(max_length=30, verbose_name='VID')),
                ('companyName', models.CharField(max_length=120, verbose_name='Company Name')),
                ('CID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.customer')),
                ('PID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.product')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=120, verbose_name='Requirement ID')),
                ('size', models.CharField(max_length=120, verbose_name='Requirement Size')),
                ('brand', models.CharField(max_length=120, verbose_name='Requirement Brand')),
                ('price', models.CharField(max_length=120, verbose_name='Requirement Price')),
                ('CID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.customer')),
            ],
        ),
    ]
