# Generated by Django 4.0.4 on 2022-05-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_ingressflow'),
        ('events', '0003_initial'),
    ]

    operations = [
    ]
