# Generated by Django 4.0.4 on 2022-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_customer_cid_alter_product_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='CID',
            field=models.CharField(default='town', max_length=1000, verbose_name='CID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PID',
            field=models.CharField(max_length=1000, verbose_name='PID'),
        ),
    ]
