# Generated by Django 4.0.4 on 2022-05-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_vendor_cid_alter_vendor_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.IntegerField(max_length=500, verbose_name='CID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.TextField(max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.TextField(max_length=120, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.TextField(max_length=15, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.TextField(max_length=300, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipCode',
            field=models.TextField(max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PID',
            field=models.IntegerField(max_length=1000, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(max_length=120, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=120, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=1000, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=60, verbose_name='Product Size'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CID',
            field=models.IntegerField(max_length=1000, verbose_name='CID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PID',
            field=models.IntegerField(max_length=1000, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VID',
            field=models.IntegerField(max_length=1000, verbose_name='VID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='companyName',
            field=models.TextField(max_length=120, verbose_name='Company Name'),
        ),
    ]
