# Generated by Django 4.0.4 on 2022-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_customer_cid_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shippingCost',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shippingTime',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='PID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VID',
            field=models.IntegerField(),
        ),
    ]
