# Generated by Django 4.0.4 on 2022-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_customer_id_delivery_id_product_id_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipCode',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shippingCost',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shippingTime',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='companyName',
            field=models.TextField(max_length=100),
        ),
    ]
