# Generated by Django 4.0.4 on 2022-05-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_customer_city_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='delivery',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vendor',
            table=None,
        ),
    ]
