# Generated by Django 4.0.4 on 2022-05-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_customer_table_alter_delivery_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='internetType',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='internetAccess',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shippingCost',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shippingTime',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=100),
        ),
    ]
