# Generated by Django 4.0.4 on 2022-05-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_customer_internettype_product_internetaccess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='PID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
