# Generated by Django 4.0.4 on 2022-05-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=60),
        ),
    ]
